on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: renderbook

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest

    container:
      image: foxsen76/archbase-builder:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build book
        run: |
          make -j 8
          cp -a ./_book /github/home/

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /github/home/_book/

      - name: Deploy
        uses: actions/deploy-pages@v4
